### ISSUE TITLE
Lunar Fireworks quest , doesn't recognise the fireworks are being fired for quest credit.

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#19]
Lunar Fireworks quest , doesn't recognize the fireworks are being fired for quest credit.

**Comment by sundayz** [comment]
Anyone has related gobjects and knows how it's supposed to work in Vanilla?

**Comment by Gutr0t** [comment]
[Quest](http://db.vanillagaming.org/?quest=8867) is supposed to ask the player to buy fireworks from the vendor, the player must cast purchased fire works into the fireworks launcher. Upon firing the quest will give credit for each individual firework launched and completed when the requirements are met:

Quest requirements:
Cast 8 of any Lunar Fireworks Rockets into the Fireworks launcher 
= Small Red Rocket [21557] , Small Green Rocket[21559] , Small Blue Rocket[21558]
and
Cast 2 of any Lunar Fireworks Cluster into the Fireworks launcher 
= Red Rocket Cluster [21576], Green Rocket Cluster[21574] , Blue Rocket Cluster[21571]


Gobjects: Fireworks launcher: [180868](http://db.vanillagaming.org/?object=180868), [180771](http://db.vanillagaming.org/?object=180771)

**Comment by natrist** [comment]
Here's a demonstration video: https://www.youtube.com/watch?v=bh8Yy6hwSKU

**Comment by sundayz** [comment]
Fixed but will need refactoring.

Cluster fireworks use implicit targeting. Rockets use explicit targeting on the NPC that is summoned by the Spell. Clusters also summon, but never use the NPC. Possible client bug?

Gameobjects will need a new Lua callback for when they are targeted by an implicit target spell in order to fix this properly. As it stands, it's a hack, but it will work.

**Comment by Nostralia** [comment]
The issue persists, no credit is given when any fireworks are shot

**Comment by Nostralia** [comment]
Works after correct lua folder contests set
